@extends('layouts.dashboard', ['title' => 'Détail du document', 'heading' => 'Détail du document'])
@section('dashboard-content')
<div class="dashboard-page-content section-page report-detail-page">
    @php($myClaim = $documentReport->claims()->where('claimant_id', auth()->id())->latest()->first())
    <a href="{{ route('citizen.search') }}" class="report-back-link">← Retour aux résultats</a>
    <div class="report-detail-grid">
        <section class="dashboard-card report-photo-card"><div class="report-photo-frame">@if ($documentReport->photo_path)<img src="{{ asset('storage/'.$documentReport->photo_path) }}" alt="Photo du document">@else<span><i class="fa-solid fa-file-lines"></i></span>@endif</div><span class="report-privacy-note"><i class="fa-solid fa-lock"></i> Données protégées</span></section>
        <section class="dashboard-card report-info-card"><div class="report-detail-header"><div><p class="dashboard-eyebrow">Document retrouvé · {{ $documentReport->document_type }}</p><h1>{{ $documentReport->owner_name }}</h1></div><span class="report-status status-{{ $documentReport->status }}">{{ $documentReport->statusLabel() }}</span></div><p class="report-intro">Ce document a été signalé à <strong>{{ $documentReport->location }}</strong>.</p><dl class="report-meta"><div><dt>Type</dt><dd>{{ $documentReport->document_type }}</dd></div><div><dt>Lieu</dt><dd>{{ $documentReport->location }}</dd></div><div><dt>Signalé le</dt><dd>{{ $documentReport->created_at->format('d/m/Y') }}</dd></div></dl>@if ($documentReport->description)<div class="report-description"><span>Description</span><p>{{ $documentReport->description }}</p></div>@endif
            @if (session('status'))<div class="profile-status">{{ session('status') }}</div>@endif
            @if ($documentReport->user_id !== auth()->id() && (!$myClaim || $myClaim->status === 'cancelled') && $documentReport->status !== 'resolved')<div class="report-action-box"><strong>Ce document vous appartient ?</strong><p>Envoyez une demande au déclarant pour organiser sa restitution.</p><form method="POST" action="{{ route('reports.claim', $documentReport) }}">@csrf<button class="dashboard-green-button">Demander la récupération</button></form></div>@elseif ($myClaim)<div class="report-action-box"><strong>Votre demande</strong><p>Statut : {{ $myClaim->status }} · Paiement : {{ $myClaim->payment_status }}</p>@if ($myClaim->status === 'accepted')<form method="POST" action="{{ route('claims.pay', $myClaim) }}">@csrf<button class="dashboard-green-button">Payer les frais de récupération</button></form>@endif @if (!in_array($myClaim->status, ['completed','cancelled']))<form method="POST" action="{{ route('claims.cancel', $myClaim) }}" class="mt-2">@csrf @method('DELETE')<button class="profile-text-link" type="submit" onclick="return confirm('Annuler cette demande ?')">Annuler la demande</button></form>@endif</div>@elseif ($documentReport->status === 'resolved')<div class="profile-status">Ce document est marqué comme restitué.</div>@endif
        </section>
    </div>
    @if ($documentReport->user_id === auth()->id() && $documentReport->claims->count())<section class="dashboard-card report-claims-card"><p class="dashboard-eyebrow">Demandes reçues</p><h2 class="dashboard-title">Personnes ayant reconnu ce document</h2>@foreach ($documentReport->claims as $claim)<div class="report-claim-row"><div><strong>{{ $claim->claimant->name }}</strong><small>Demande : {{ $claim->status }}</small></div>@if ($claim->status === 'pending')<form method="POST" action="{{ route('claims.accept', $claim) }}">@csrf<button class="dashboard-green-button">Accepter</button></form>@endif</div>@endforeach</section>@endif
</div>
@endsection
